app_version: 0.4.7
capabilities: []
categories:
- media
changelog_url: https://github.com/terralayer/ScarletX/releases
date_added: '2026-08-30'
description: Self-hosted adult scene management and automation with TPDB metadata, monitoring, built-in downloading, imports, library management, and playback.
home: https://github.com/terralayer/ScarletX
host_mounts: []
icon: https://raw.githubusercontent.com/terralayer/ScarletX/main/docs/images/scarletx-icon.svg
keywords:
- media
- adult
- scenes
- automation
- tpdb
lib_version: 2.3.12
lib_version_hash: 1a258793b511e2d91cb0f0381b142e793236892f6619d6e76cec158c95e5ee1d
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: scarletx
run_as_context:
- description: Container [scarletx-0.4.7-backend] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [scarletx-0.4.7-web] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://raw.githubusercontent.com/terralayer/ScarletX/main/docs/images/scarletx-dashboard.png
- https://raw.githubusercontent.com/terralayer/ScarletX/main/docs/images/scarletx-scenes.png
sources:
- https://github.com/terralayer/ScarletX
title: ScarletX
train: community
version: 1.0.14
